### ISSUE TITLE
The cli_dataset_create.py file was not found

### ISSUE THREAD

**Issue by GuanghuiSong** [microsoft/mttl#119]
Great work! The cli_dataset_create.py file was not found. Can you provide code for data downloading and processing?

**Comment by sordonia** [comment]
Sure, sorry we will update the README, the script now is `create_flan.py`

**Comment by sordonia** [comment]
merged, let me know if it worked!

**Comment by GuanghuiSong** [comment]
The dataset should now download successfully, but the train_experts_main.py and run_mbc_clustering.py files are not found, so you may need to update the readme and check the files.Thanks!

**Comment by GuanghuiSong** [comment]
@sordonia

**Comment by shuishen112** [comment]
@GuanghuiSong  the new file is train_experts.py and mbc_clustering.py. sry, we will update it ASAP.

**Comment by sordonia** [comment]
somehow i don't get notifications... sorry for late answer, will PR the change
