### ISSUE TITLE
Issues when finetuning pretrained lora checkpoint for downstream tasks.

### ISSUE THREAD

**Issue by prateeky2806** [microsoft/mttl#48]
Hi Lucas,

I was trying to run the MHR codebase to finetune on a downstream task after loading the pretrained lora checkpoint provided [here](https://huggingface.co/pclucas14/multi-head-routing/blob/main/t0-dataset/t0-3b/lora/lora-rank1). I am not able to load the pretrained lora checkpoints into the model and I getting some shape mismatch errors. I am pretty sure I am messing up something with the config files and hyperparameters setting. Would it be possible for you to provide a command that can be used to FT lora checkpoint on any downstream task say RTE? 

I was able to load the poly checkpoint and finetune that further using the provided scripts [here](https://github.com/microsoft/mttl/blob/main/projects/mhr/scripts/finetune/few_shot_t0_tm0d_with_poly.sh). It would be great if you can add scripts to finetune lora, ia3, and mhr pretrained checkpoints. 

Thanks,
Prateek

**Comment by pclucas14** [comment]
Hi Prateek, 

Sorry for the late reply; did you manage to solve this issue ?
