### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by harsha-moparthy** [microsoft/mttl#53]
Hi, it will be very helpful if some documentation is added which include how to run MBC and other variants of adapters and router

**Comment by matheper** [comment]
Hi @harsha-moparthy,
You can find instructions on how to prepare the dataset, train and evaluate adapters in [projects/modular_llm](https://github.com/microsoft/mttl/blob/main/projects/modular_llm/README.md).
We are working to add more detailed steps to our documentation soon.

**Comment by sordonia** [comment]
Hi, we just released some new doc!

let us know if that works
