### ISSUE TITLE
Packed batch

### ISSUE THREAD

**Issue by sordonia** [microsoft/mttl#98]
right now, when packing, the output batch contains a bunch of fields that are in the input batch ,e.g. 'task_name' and does not call them 'task_names' like the standard output batch, this should break the behavior for training MoE models

consider creating a dataclass DefaultBatch with the required fields

**Comment by pclucas14** [comment]
Can you expand a bit what you mean by this ? Setting `pack_sequences=True` should augment `RoutingInfo` with 3 things : `packed_seq_lens`, `seq_lens` and `packed_attn_mask`, all of which should not interfere with e.g. `task_name`

**Comment by sordonia** [comment]
do you have "task_names" in your output_batch when you collate?

**Comment by pclucas14** [comment]
Yes

**Comment by sordonia** [comment]
you sure? :D

**Comment by sordonia** [comment]
mea culpas , closing
